---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
    name: default-http-backend
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-default-http-backend"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
  {{- if .Values.defaultBackend.namespace }}
  namespace: {{.Values.defaultBackend.namespace}}
  {{- end}}
spec:
  replicas: {{.Values.defaultBackend.replicas}}
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: {{.Values.defaultBackend.image}}:{{.Values.defaultBackend.version}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: {{.Values.defaultBackend.resources.cpu}}
            memory: {{.Values.defaultBackend.resources.memory}}
          requests:
            cpu: {{.Values.defaultBackend.resources.cpu}}
            memory: {{.Values.defaultBackend.resources.memory}}
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
    name: default-http-backend
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-default-http-backend"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
  {{- if .Values.defaultBackend.namespace }}
  namespace: {{.Values.defaultBackend.namespace}}
  {{- end}}
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: default-http-backend
